### ISSUE TITLE
不是bug,但是也是细节

### ISSUE THREAD

**Issue by niuxiaoniu0527** [Wzxhaha/WWeChat#1]
您好,刚刚开始关注您的博客,看到了仿微信的这篇文章,但是发现了一个小小的问题,您讲解的是LeanCloud吧?但是应该是笔误,写成了LearnCloud.希望您能收到吧!

**Comment by wzxha** [comment]
谢谢你的反馈！刚开始的时候看错了一直以为是LearnCloud...后来才发现是LeanCloud，可能还有些部分没改正。
