### ISSUE TITLE
通讯录点击后会变大，但不能进入聊天界面

### ISSUE THREAD

**Issue by iVincentX** [Wzxhaha/WWeChat#2]
一直在关注你在简书上的更新，看文章说你已经实现了通讯功能，但我从github上下下来的代码，运行后，如题，很多点击都没有反应啊

**Comment by wzxha** [comment]
谢谢反馈！请问是刚才下的版本吗？

**Comment by iVincentX** [comment]
是的呢

**Comment by wzxha** [comment]
好吧～是因为我用的融云做IM，没有历史会话存在融云的服务器，所以必须用另一个号和它聊天后才会出现会话(还是说4s收不到)。这个将尽快优化。

还有很多点击是没做的，目前只完成了文字通讯

而通讯录的点击变大...我这一直没遇到过..后期还是创建一个Cell.xib吧。

**Comment by iVincentX** [comment]
持续关注中..

**Comment by rzning18** [comment]
楼主 请问登录怎么登录不上去

**Comment by wzxha** [comment]
WWeChat重构，测试帐号全部删除了，今天晚上之前会上传
